package com.b2i.serviceorganisation.bootstrap;

import com.b2i.serviceorganisation.dto.request.CountryRequest;
import com.b2i.serviceorganisation.service.CountryServiceImplementation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class CountryBootstrap {

    @Autowired
    private CountryServiceImplementation countryServiceImplementation;

    public void seed() {

        if(countryServiceImplementation.countAll() == 0L) {

            countryServiceImplementation.createCountry(new CountryRequest("AFGHANISTAN"));
            countryServiceImplementation.createCountry(new CountryRequest("AFRIQUE DU SUD"));
            countryServiceImplementation.createCountry(new CountryRequest("ALBANIE"));
            countryServiceImplementation.createCountry(new CountryRequest("ALGÉRIE"));
            countryServiceImplementation.createCountry(new CountryRequest("ALLEMAGNE"));
            countryServiceImplementation.createCountry(new CountryRequest("ANDORRE"));
            countryServiceImplementation.createCountry(new CountryRequest("ANGOLA"));
            countryServiceImplementation.createCountry(new CountryRequest("ANTIGUA-ET-BARBUDA"));
            countryServiceImplementation.createCountry(new CountryRequest("ARABIE SAOUDITE"));
            countryServiceImplementation.createCountry(new CountryRequest("ARGENTINE"));
            countryServiceImplementation.createCountry(new CountryRequest("ARMÉNIE"));
            countryServiceImplementation.createCountry(new CountryRequest("AUSTRALIE"));
            countryServiceImplementation.createCountry(new CountryRequest("AUTRICHE"));
            countryServiceImplementation.createCountry(new CountryRequest("AZERBAÏDJAN"));
            countryServiceImplementation.createCountry(new CountryRequest("BAHAMAS"));
            countryServiceImplementation.createCountry(new CountryRequest("BAHREÏN"));
            countryServiceImplementation.createCountry(new CountryRequest("BANGLADESH"));
            countryServiceImplementation.createCountry(new CountryRequest("BARBADE"));
            countryServiceImplementation.createCountry(new CountryRequest("BELAU - PALAOS"));
            countryServiceImplementation.createCountry(new CountryRequest("BELGIQUE"));
            countryServiceImplementation.createCountry(new CountryRequest("BÉLIZE"));
            countryServiceImplementation.createCountry(new CountryRequest("BÉNIN"));
            countryServiceImplementation.createCountry(new CountryRequest("BHOUTAN"));
            countryServiceImplementation.createCountry(new CountryRequest("BIÉLORUSSIE"));
            countryServiceImplementation.createCountry(new CountryRequest("BIRMANIE"));
            countryServiceImplementation.createCountry(new CountryRequest("BOLIVIE"));
            countryServiceImplementation.createCountry(new CountryRequest("BOSNIE-HERZÉGOVINE"));
            countryServiceImplementation.createCountry(new CountryRequest("BOTSWANA"));
            countryServiceImplementation.createCountry(new CountryRequest("BRÉSIL"));
            countryServiceImplementation.createCountry(new CountryRequest("BRUNEI"));
            countryServiceImplementation.createCountry(new CountryRequest("BULGARIE"));
            countryServiceImplementation.createCountry(new CountryRequest("BURKINA FASO"));
            countryServiceImplementation.createCountry(new CountryRequest("BURUNDI"));
            countryServiceImplementation.createCountry(new CountryRequest("CAMBODGE"));
            countryServiceImplementation.createCountry(new CountryRequest("CAMEROUN"));
            countryServiceImplementation.createCountry(new CountryRequest("CANADA"));
            countryServiceImplementation.createCountry(new CountryRequest("CAP-VERT"));
            countryServiceImplementation.createCountry(new CountryRequest("CENTRAFRIQUE"));
            countryServiceImplementation.createCountry(new CountryRequest("CHILI"));
            countryServiceImplementation.createCountry(new CountryRequest("CHINOIS"));
            countryServiceImplementation.createCountry(new CountryRequest("CHYPRE"));
            countryServiceImplementation.createCountry(new CountryRequest("COLOMBIE"));
            countryServiceImplementation.createCountry(new CountryRequest("COMORRES"));
            countryServiceImplementation.createCountry(new CountryRequest("CONGO BRAZZAVILE"));
            countryServiceImplementation.createCountry(new CountryRequest("RÉPUBLIQUE DÉMOCRATIQUE DU CONGO"));
            countryServiceImplementation.createCountry(new CountryRequest("CORÉE DU NORD"));
            countryServiceImplementation.createCountry(new CountryRequest("CORÉE DU SUD"));
            countryServiceImplementation.createCountry(new CountryRequest("COSTA RICA"));
            countryServiceImplementation.createCountry(new CountryRequest("CÔTE D'IVOIRE"));
            countryServiceImplementation.createCountry(new CountryRequest("CROATIE"));
            countryServiceImplementation.createCountry(new CountryRequest("CUBA"));
            countryServiceImplementation.createCountry(new CountryRequest("DANEMARK"));
            countryServiceImplementation.createCountry(new CountryRequest("DJIBOUTI"));
            countryServiceImplementation.createCountry(new CountryRequest("DOMINIQUE"));
            countryServiceImplementation.createCountry(new CountryRequest("ÉGYPTE"));
            countryServiceImplementation.createCountry(new CountryRequest("ÉMIRATS ARABES UNIS"));
            countryServiceImplementation.createCountry(new CountryRequest("ÉQUATEUR"));
            countryServiceImplementation.createCountry(new CountryRequest("ÉRYTHRÉE"));
            countryServiceImplementation.createCountry(new CountryRequest("ESPAGNE"));
            countryServiceImplementation.createCountry(new CountryRequest("ESTONIE"));
            countryServiceImplementation.createCountry(new CountryRequest("ÉTATS-UNIS"));
            countryServiceImplementation.createCountry(new CountryRequest("ÉTHIOPIE"));
            countryServiceImplementation.createCountry(new CountryRequest("ÎLES FIDJI"));
            countryServiceImplementation.createCountry(new CountryRequest("FINLANDE"));
            countryServiceImplementation.createCountry(new CountryRequest("FRANCE"));
            countryServiceImplementation.createCountry(new CountryRequest("GABON"));
            countryServiceImplementation.createCountry(new CountryRequest("GAMBIE"));
            countryServiceImplementation.createCountry(new CountryRequest("GÉORGIE"));
            countryServiceImplementation.createCountry(new CountryRequest("GHANA"));
            countryServiceImplementation.createCountry(new CountryRequest("GRÈCE"));
            countryServiceImplementation.createCountry(new CountryRequest("GRENADE"));
            countryServiceImplementation.createCountry(new CountryRequest("GUATÉMALA"));
            countryServiceImplementation.createCountry(new CountryRequest("GUINÉE-BISSAU"));
            countryServiceImplementation.createCountry(new CountryRequest("GUINÉE CONAKRY"));
            countryServiceImplementation.createCountry(new CountryRequest("GUINÉE ÉQUATORIALE"));
            countryServiceImplementation.createCountry(new CountryRequest("GUYANA"));
            countryServiceImplementation.createCountry(new CountryRequest("HAÏTI"));
            countryServiceImplementation.createCountry(new CountryRequest("HONDURAS"));
            countryServiceImplementation.createCountry(new CountryRequest("HONGRIE"));
            countryServiceImplementation.createCountry(new CountryRequest("INDE"));
            countryServiceImplementation.createCountry(new CountryRequest("INDONÉSIE"));
            countryServiceImplementation.createCountry(new CountryRequest("IRAK"));
            countryServiceImplementation.createCountry(new CountryRequest("IRAN"));
            countryServiceImplementation.createCountry(new CountryRequest("IRLANDE"));
            countryServiceImplementation.createCountry(new CountryRequest("ISLANDE"));
            countryServiceImplementation.createCountry(new CountryRequest("ISRAËL"));
            countryServiceImplementation.createCountry(new CountryRequest("ITALIE"));
            countryServiceImplementation.createCountry(new CountryRequest("JAMAÏQUE"));
            countryServiceImplementation.createCountry(new CountryRequest("JAPON"));
            countryServiceImplementation.createCountry(new CountryRequest("JORDANIE"));
            countryServiceImplementation.createCountry(new CountryRequest("KAZAKHSTAN"));
            countryServiceImplementation.createCountry(new CountryRequest("KENYA"));
            countryServiceImplementation.createCountry(new CountryRequest("KIRGHIZISTAN"));
            countryServiceImplementation.createCountry(new CountryRequest("KIRIBATI"));
            countryServiceImplementation.createCountry(new CountryRequest("KOSOVO"));
            countryServiceImplementation.createCountry(new CountryRequest("KOWEÏT"));
            countryServiceImplementation.createCountry(new CountryRequest("LAOS"));
            countryServiceImplementation.createCountry(new CountryRequest("LESOTHO"));
            countryServiceImplementation.createCountry(new CountryRequest("LETTONIE"));
            countryServiceImplementation.createCountry(new CountryRequest("LIBAN"));
            countryServiceImplementation.createCountry(new CountryRequest("LIBERIA"));
            countryServiceImplementation.createCountry(new CountryRequest("LIBYE"));
            countryServiceImplementation.createCountry(new CountryRequest("LIECHTENSTEIN"));
            countryServiceImplementation.createCountry(new CountryRequest("LITUANIE"));
            countryServiceImplementation.createCountry(new CountryRequest("LUXEMBOURG"));
            countryServiceImplementation.createCountry(new CountryRequest("MACÉDOINE DU NORD"));
            countryServiceImplementation.createCountry(new CountryRequest("MADAGASCAR"));
            countryServiceImplementation.createCountry(new CountryRequest("MALAISIE"));
            countryServiceImplementation.createCountry(new CountryRequest("MALAWI"));
            countryServiceImplementation.createCountry(new CountryRequest("MALDIVES"));
            countryServiceImplementation.createCountry(new CountryRequest("MALI"));
            countryServiceImplementation.createCountry(new CountryRequest("MALTE"));
            countryServiceImplementation.createCountry(new CountryRequest("MAROC"));
            countryServiceImplementation.createCountry(new CountryRequest("MARSHALL"));
            countryServiceImplementation.createCountry(new CountryRequest("ÎLES MAURICES"));
            countryServiceImplementation.createCountry(new CountryRequest("MAURITANIE"));
            countryServiceImplementation.createCountry(new CountryRequest("MEXIQUE"));
            countryServiceImplementation.createCountry(new CountryRequest("MICRONÉSIE"));
            countryServiceImplementation.createCountry(new CountryRequest("MOLDAVIE"));
            countryServiceImplementation.createCountry(new CountryRequest("MONACO"));
            countryServiceImplementation.createCountry(new CountryRequest("MONGOLIE"));
            countryServiceImplementation.createCountry(new CountryRequest("MONTÉNÉGRO"));
            countryServiceImplementation.createCountry(new CountryRequest("MOZAMBIQUE"));
            countryServiceImplementation.createCountry(new CountryRequest("NAMIBIE"));
            countryServiceImplementation.createCountry(new CountryRequest("NAURU"));
            countryServiceImplementation.createCountry(new CountryRequest("NÉPAL"));
            countryServiceImplementation.createCountry(new CountryRequest("NICARAGUA"));
            countryServiceImplementation.createCountry(new CountryRequest("NIGER"));
            countryServiceImplementation.createCountry(new CountryRequest("NIGÉRIA"));
            countryServiceImplementation.createCountry(new CountryRequest("NORVÈGE"));
            countryServiceImplementation.createCountry(new CountryRequest("NOUVELLE-ZÉLANDE"));
            countryServiceImplementation.createCountry(new CountryRequest("OMAN"));
            countryServiceImplementation.createCountry(new CountryRequest("OUGANDA"));
            countryServiceImplementation.createCountry(new CountryRequest("OUZBÉKISTAN"));
            countryServiceImplementation.createCountry(new CountryRequest("PAKISTAN"));
            countryServiceImplementation.createCountry(new CountryRequest("PANAMA"));
            countryServiceImplementation.createCountry(new CountryRequest("PAPOUASIE NOUVELLE-GUINÉE"));
            countryServiceImplementation.createCountry(new CountryRequest("PARAGUAYS"));
            countryServiceImplementation.createCountry(new CountryRequest("PAYS-BAS"));
            countryServiceImplementation.createCountry(new CountryRequest("PÉROU"));
            countryServiceImplementation.createCountry(new CountryRequest("PHILIPPINES"));
            countryServiceImplementation.createCountry(new CountryRequest("POLOGNE"));
            countryServiceImplementation.createCountry(new CountryRequest("PORTUGAL"));
            countryServiceImplementation.createCountry(new CountryRequest("QATAR"));
            countryServiceImplementation.createCountry(new CountryRequest("RÉPUBLIQUE DOMINICAINE"));
            countryServiceImplementation.createCountry(new CountryRequest("RÉPUBLIQUE TCHÈQUE"));
            countryServiceImplementation.createCountry(new CountryRequest("ROUMANIE"));
            countryServiceImplementation.createCountry(new CountryRequest("ROYAUME-UNI"));
            countryServiceImplementation.createCountry(new CountryRequest("RUSSIE"));
            countryServiceImplementation.createCountry(new CountryRequest("RWANDA"));
            countryServiceImplementation.createCountry(new CountryRequest("SAINT-CHRISTOPHE-ET-NIÉVÈS"));
            countryServiceImplementation.createCountry(new CountryRequest("SAINTE-LUCIE"));
            countryServiceImplementation.createCountry(new CountryRequest("SAINT-MARIN"));
            countryServiceImplementation.createCountry(new CountryRequest("SAINT-VINCENT-ET-LES-GRENADINES"));
            countryServiceImplementation.createCountry(new CountryRequest("ÎLES SALOMON"));
            countryServiceImplementation.createCountry(new CountryRequest("SAO TOMÉ ET PRINCIPES"));
            countryServiceImplementation.createCountry(new CountryRequest("SALVADOR"));
            countryServiceImplementation.createCountry(new CountryRequest("SAMOA OCCIDENTALES"));
            countryServiceImplementation.createCountry(new CountryRequest("SÉNÉGAL"));
            countryServiceImplementation.createCountry(new CountryRequest("SERBIE"));
            countryServiceImplementation.createCountry(new CountryRequest("SEYCHELLES"));
            countryServiceImplementation.createCountry(new CountryRequest("SIERRA LEONE"));
            countryServiceImplementation.createCountry(new CountryRequest("SINGAPOUR"));
            countryServiceImplementation.createCountry(new CountryRequest("SLOVAQUIE"));
            countryServiceImplementation.createCountry(new CountryRequest("SLOVÉNIE"));
            countryServiceImplementation.createCountry(new CountryRequest("SOMALIE"));
            countryServiceImplementation.createCountry(new CountryRequest("SOUDAN"));
            countryServiceImplementation.createCountry(new CountryRequest("SOUDAN DU SUD"));
            countryServiceImplementation.createCountry(new CountryRequest("SRI LANKA"));
            countryServiceImplementation.createCountry(new CountryRequest("SUÈDE"));
            countryServiceImplementation.createCountry(new CountryRequest("SUISSE"));
            countryServiceImplementation.createCountry(new CountryRequest("SURINAM"));
            countryServiceImplementation.createCountry(new CountryRequest("SWAZILAND"));
            countryServiceImplementation.createCountry(new CountryRequest("SYRIE"));
            countryServiceImplementation.createCountry(new CountryRequest("TADJIKISTAN"));
            countryServiceImplementation.createCountry(new CountryRequest("TANZANIE"));
            countryServiceImplementation.createCountry(new CountryRequest("TCHAD"));
            countryServiceImplementation.createCountry(new CountryRequest("TIMOR ORIENTAL"));
            countryServiceImplementation.createCountry(new CountryRequest("THAÏLANDE"));
            countryServiceImplementation.createCountry(new CountryRequest("TOGO"));
            countryServiceImplementation.createCountry(new CountryRequest("TONGA"));
            countryServiceImplementation.createCountry(new CountryRequest("TRINITÉ-ET-TOBAGO"));
            countryServiceImplementation.createCountry(new CountryRequest("TUNISIE"));
            countryServiceImplementation.createCountry(new CountryRequest("TURKMÉNISTAN"));
            countryServiceImplementation.createCountry(new CountryRequest("TURQUIE"));
            countryServiceImplementation.createCountry(new CountryRequest("TUVALU"));
            countryServiceImplementation.createCountry(new CountryRequest("UKRAINE"));
            countryServiceImplementation.createCountry(new CountryRequest("URUGUAY"));
            countryServiceImplementation.createCountry(new CountryRequest("VANUATU"));
            countryServiceImplementation.createCountry(new CountryRequest("VATICAN"));
            countryServiceImplementation.createCountry(new CountryRequest("VENEZUELA"));
            countryServiceImplementation.createCountry(new CountryRequest("VIETNAM"));
            countryServiceImplementation.createCountry(new CountryRequest("YÉMEN"));
            countryServiceImplementation.createCountry(new CountryRequest("ZAMBIE"));
            countryServiceImplementation.createCountry(new CountryRequest("ZIMBABWE"));
        }
    }
}
